<?php

/**
 * @file
 * Provides a remote stream wrapper and file field integration.
 *
 * @todo Add a 'Remote URL' file field widget.
 */

/**
 * Stream wrapper type flag -- visible and readable using remote files that act like local files.
 */
define('STREAM_WRAPPERS_REMOTE', STREAM_WRAPPERS_LOCAL | STREAM_WRAPPERS_READ | STREAM_WRAPPERS_VISIBLE);

/**
 * Implements hook_menu().
 */
function remote_stream_wrapper_menu() {
  $items = array();

  $items['file/add/remote'] = array(
    'title' => 'Remote',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('remote_stream_wrapper_file_add_form'),
    'access callback' => 'remote_stream_wrapper_media_browser_plugin_access',
    'type' => MENU_LOCAL_TASK,
  );

  // Add image style generation paths for external URLs.
  if (module_exists('image')) {
    $wrappers = file_get_remote_stream_wrappers();
    $directory_path = file_stream_wrapper_get_instance_by_scheme(file_default_scheme())->getDirectoryPath();
    $pos = count(explode('/', $directory_path)) + 1;
    $item = array(
      'page callback' => 'remote_stream_wrapper_image_style_deliver',
      'page arguments' => array($pos, $pos + 1),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      'file' => 'remote_stream_wrapper.image.inc',
    );
    foreach (array_keys($wrappers) as $scheme) {
      $items[$directory_path . '/styles/%image_style/' . $scheme] = $item;
    }
  }

  return $items;
}

/**
 * Implements hook_permission().
 */
function remote_stream_wrapper_permission() {
  $permission = array();

  if (module_exists('media')) {
    $permission['add media from remote urls'] = array(
      'title' => t('Add media from remote URLs'),
      'description' => t('Add media from remote URLs.'),
    );
  }

  return $permission;
}

/**
 * Implements hook_stream_wrappers().
 */
function remote_stream_wrapper_stream_wrappers() {
  $info['http'] = array(
    'name' => t('HTTP URLs'),
    'class' => 'DrupalRemoteStreamWrapper',
    'description' => t('Remote files.'),
    'type' => STREAM_WRAPPERS_REMOTE,
    'remote' => TRUE,
  );
  $info['https'] = $info['http'];
  $info['https']['name'] = t('HTTPS URLs');
  $info['feed'] = $info['http'];
  $info['feed']['name'] = t('Feed URLs');

  $info['local'] = array(
    'name' => t('Local paths'),
    'class' => 'DrupalRemoteLocalStreamWrapper',
    'description' => t('Local paths as remote files.'),
    'type' => STREAM_WRAPPERS_REMOTE,
    'remote' => TRUE,
  );

  return $info;
}

/**
 * Return a list of remote stream wrappers.
 */
function file_get_remote_stream_wrappers() {
  $wrappers = file_get_stream_wrappers(STREAM_WRAPPERS_REMOTE);
  foreach ($wrappers as $scheme => $wrapper) {
    if (empty($wrapper['remote'])) {
      unset($wrappers[$scheme]);
    }
  }
  //$wrappers = array_diff_key($wrappers, file_get_stream_wrappers(STREAM_WRAPPERS_LOCAL_NORMAL));
  return $wrappers;
}

/**
 * Check if a stream wrapper scheme is a remote stream wrapper.
 */
function file_is_scheme_remote($scheme) {
  $wrappers = file_get_remote_stream_wrappers();
  return isset($wrappers[$scheme]);
}

/**
 * Implements hook_file_url_alter().
 */
function remote_stream_wrapper_file_url_alter(&$uri) {
  $scheme = file_uri_scheme($uri);
  $wrappers = file_get_remote_stream_wrappers();
  if ($scheme && isset($wrappers[$scheme]) && strpos($uri, "$scheme://styles/") === 0) {
    $uri = file_default_scheme() . '://' . file_uri_target($uri);
  }
}

/**
 * Copy of image_style_path() for use with remote images.
 *
 * When image_style_path() is give a file like 'http://example.com/image.png'
 * it is converted into 'http://styles/stylename/http/example.com/image.png'
 * which will fail image_style_deliver().
 */
function remote_stream_wrapper_image_style_path($style_name, $uri) {
  // Force the image style to be returned with the default file scheme, but
  // with the file's original scheme in the path.
  return file_default_scheme() . '://styles/' . $style_name . '/' . file_uri_scheme($uri) . '/' . file_uri_target($uri);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Manually add support for the remote stream wrapper in file fields since
 * it is read-only.
 */
function remote_stream_wrapper_form_field_ui_field_edit_form_alter(&$form, &$form_state) {
  if ($form['#field']['type'] == 'file' || $form['#field']['type'] == 'image') {
    $form['field']['settings']['uri_scheme']['#description'] .= ' ' . t('This only applies to uploaded files and not remote files.');
  }
}

/**
 * Validation callback for remote URLs.
 */
function remote_stream_wrapper_validate_url($element, &$form_state) {
  foreach (array('scheme', 'valid', 'exists') as $check) {
    $message = _remote_stream_wrapper_check_uri($check, $element['#value']);
    if ($message !== NULL) {
      form_error($element, $message);
      return;
    }
  }
}

/**
 * Checks URI.
 *
 * @param string $check
 *   Check type, either 'scheme', 'valid', or 'exists'.
 * @param string $uri
 *
 * @return null|string
 *   NULL if check passed, or error message.
 */
function _remote_stream_wrapper_check_uri($check, $uri) {
  if ($wrapper = file_stream_wrapper_get_instance_by_uri($uri)) {
    switch ($check) {
      case 'scheme':
        if (file_stream_wrapper_valid_scheme(file_uri_scheme($uri))) {
          return NULL;
        }
        return t('Remote URLs with the %scheme scheme are not supported.', array('%scheme' => file_uri_scheme($uri)));

      case 'valid':
        if ($wrapper instanceof DrupalRemoteStreamWrapper) {
          if (valid_url($uri, TRUE)) {
            return NULL;
          }
        }
        elseif ($wrapper instanceof DrupalRemoteLocalStreamWrapper) {
          $options = drupal_parse_url(substr($uri, 8));
          if (trim($options['path']) !== '') {
            return NULL;
          }
        }
        return t('Invalid URL %url.', array('%url' => $uri));

      case 'exists':
        if ($wrapper instanceof DrupalRemoteLocalStreamWrapper) {
          $uri = DrupalRemoteLocalStreamWrapper::localToRemote($uri);
        }
        $request = drupal_http_request($uri, array('method' => 'HEAD'));
        if (empty($request->error)) {
          return NULL;
        }
        return t('Unable to fetch file from URL %url (error @code: %error).', array('%url' => $uri, '@code' => $request->code, '%error' => $request->error));
    }
  }
  return t('Invalid URL %url.', array('%url' => $uri));
}

/**
 * Load a file object by URI.
 *
 * @param string $uri
 *   A string containing the URI, path, or filename.
 *
 * @return
 *   A file object, or FALSE if not found.
 */
function remote_stream_wrapper_file_load_by_uri($uri) {
  $uri = file_stream_wrapper_uri_normalize($uri);
  $files = entity_load('file', FALSE, array('uri' => $uri));
  return !empty($files) ? reset($files) : FALSE;
}

/**
 * Helper functon to assemble a new file entity object by URI.
 *
 * @param string $uri
 *   A string containing the URI, path, or filename.
 */
function remote_stream_wrapper_file_create_by_uri($uri) {
  $uri = file_stream_wrapper_uri_normalize($uri);

  $file = new stdClass();
  $file->fid = NULL;
  $file->uri = $uri;
  $file->filename = basename($file->uri);
  $file->filemime = file_get_mimetype($file->uri);

  // If URL targeting a HTML page, the mime can have charset inside, for
  // example, it can be "text/html; charset=utf-8".
  $mime_parts = explode(';', trim($file->filemime));
  $file->filemime = $mime_parts[0];

  $file->uid = $GLOBALS['user']->uid;
  $file->status = FILE_STATUS_PERMANENT;
  return $file;
}

/**
 * Implements hook_media_browser_plugin_info().
 */
function remote_stream_wrapper_media_browser_plugin_info() {
  $plugins['remote_file'] = array(
    'title' => t('Remote URL'),
    'class' => 'RemoteStreamWrapperMediaBrowser',
    // Support for Media 1.x browser plugin API.
    '#title' => t('Remote URL'),
    'access callback' => 'remote_stream_wrapper_media_browser_plugin_access',
  );
  return $plugins;
}

/**
 * Media 1.x browser plugin access callback.
 *
 * Duplicate of RemoteStreamWrapperMediaBrowser::access().
 */
function remote_stream_wrapper_media_browser_plugin_access() {
  return user_access('administer files') || user_access('add media from remote urls');
}

/**
 * Implements hook_media_browser_plugin_view().
 */
function remote_stream_wrapper_media_browser_plugin_view($plugin_name, $params) {
  if ($plugin_name == 'remote_file') {
    if (remote_stream_wrapper_media_browser_plugin_access()) {
      $params += array('types' => array());
      $form = drupal_get_form('remote_stream_wrapper_file_add_form', $params);
      return array(
        '#title' => t('Remote URL'),
        'form' => array($form),
      );
    }
  }
}

/**
 * Provides a form for adding media items from remote URLs.
 *
 * @see remote_stream_wrapper_media_browser_form_submit()
 */
function remote_stream_wrapper_file_add_form($form, &$form_state, array $options = array()) {
  $form['url'] = array(
    '#type' => 'textfield',
    '#title' => 'URL',
    '#description' => t('Allowed values:
<ul>
  <li>any absolute URLs, for example "http://example.com/"</li>
  <li>internal paths starting with "local://" prefix, for example "local://node/123" or "local://node/123?foo=bar&baz=qux"
</ul>'),
    '#attributes' => array('class' => array('media-add-from-remote-url')),
    '#maxlength' => 255, // Maximum length of {file_managed}.uri
    '#element_validate' => array('remote_stream_wrapper_validate_url'),
    '#required' => TRUE,
  );

  // @todo Validate against file field allowed types.
  $form['#validators'] = array();

  if (isset($form_state['previous_url']) && $form_state['previous_url'] == $form_state['values']['url']) {
    $form['mime'] = array(
      '#type' => 'textfield',
      '#title' => t('Mime'),
      '#required' => TRUE,
      '#default_value' => $form_state['values']['mime'],
    );
    include_once DRUPAL_ROOT . '/includes/file.mimetypes.inc';
    $mimetypes = file_mimetype_mapping();
    $form['mimetype_mapping'] = array(
      '#type' => 'fieldset',
      '#title' => t('Mimetype List'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    $form['mimetype_mapping']['mapping'] = array(
      '#theme' => 'item_list',
      '#items' => $mimetypes['mimetypes'],
    );
    $form['type'] = array(
      '#type' => 'select',
      '#title' => t('Type'),
      '#required' => TRUE,
      '#options' => file_entity_type_get_names(),
      '#default_value' => $form_state['values']['type'],
    );
  }

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

/**
 * Validate handler for the "add remote file" form.
 */
function remote_stream_wrapper_file_add_form_validate(&$form, &$form_state) {
  if (form_get_errors()) {
    return;
  }
  try {
    $file = remote_stream_wrapper_file_load_by_uri($form_state['values']['url']);
    if ($file) {
      $edit_path = 'file/' . $file->fid . '/edit';
      form_error($form['url'], t('A file with given URL is already exist. You can edit it at !link', array('!link' => l($edit_path, $edit_path))));
    }
    else {
      include_once DRUPAL_ROOT . '/includes/file.mimetypes.inc';
      $mimetypes = file_mimetype_mapping();
      $first_url_validation = empty($form_state['previous_url']) || $form_state['previous_url'] != $form_state['values']['url'];
      if ($first_url_validation) {
        $form_state['previous_url'] = $form_state['values']['url'];
        $form_state['rebuild'] = TRUE;
        // Try to detect file type automatically.
        $file = remote_stream_wrapper_file_create_by_uri($form_state['values']['url']);
        $form_state['values']['mime'] = $file->filemime;
        if (in_array($form_state['values']['mime'], $mimetypes['mimetypes'])) {
          drupal_set_message(t('Please ensure that file mime is correct.'));
        }
        else {
          drupal_set_message(t('Auto-detected file mime is not correct. Please change it.'), 'warning');
        }
        if ($file_type = file_get_type($file)) {
          $form_state['values']['type'] = $file_type;
          drupal_set_message(t('Please ensure that file type is correct.'));
        }
        else {
          $form_state['values']['type'] = NULL;
          drupal_set_message(t('Drupal was not able to detect the file type. Please select type from the list.'), 'warning');
        }
      }
    }
  } catch (Exception $e) {
    form_error($form['url'], $e->getMessage());
    return;
  }
}

/**
 * Save a file record based on a remote URL.
 *
 * @see remote_stream_wrapper_media_browser_form()
 * @see file_save()
 * @see DrupalRemoteStreamWrapper
 */
function remote_stream_wrapper_file_add_form_submit($form, &$form_state) {
  $uri = $url = $form_state['values']['url'];

  try {
    $file = remote_stream_wrapper_file_create_by_uri($uri);

    // Use form values for type and mime.
    $file->type = $form_state['values']['type'];
    $file->filemime = $form_state['values']['mime'];

    file_save($file);
  }
  catch (Exception $e) {
    form_set_error('url', $e->getMessage());
    return;
  }

  if (empty($file->fid)) {
    form_set_error('url', t('Unable to add file from URL %file.', array('%file' => $url)));
    return;
  }
  else {
    $form_state['file'] = $file;
  }

  if (drupal_valid_path('file/' . $file->fid . '/edit')) {
    $destination = array('destination' => 'admin/content/file');
    if (isset($_GET['destination'])) {
      $destination = drupal_get_destination();
      unset($_GET['destination']);
    }
    $form_state['redirect'] = array('file/' . $file->fid . '/edit', array('query' => $destination));
  }
  else {
    $form_state['redirect'] = 'admin/content/file';
  }
}
